
package centsible.frames.admin;

import centsible.frames.user.*;
import centsible.functions.ChangePasswordFunction;
import centsible.functions.UserFunctions;

/**
 *
 * @author Venthings
 */
public class ChangeAdminPassword extends javax.swing.JFrame {

    int xMouse = 0, yMouse = 0;
    
    public static String username;
    
    int oldPassFlag = 0, passFlag = 0, conPassFlag = 0;
    
    String oldPass = "", password = "", conPass = "";
    
    ChangePasswordFunction cp;
    public ChangeAdminPassword(String username) {
        initComponents();
        setLocationRelativeTo(null);
        txtOldPass.getParent().requestFocus();
        cp = new ChangePasswordFunction(txtOldPass, txtPass, txtConPass);
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnConfirm = new centsible.components.CustomButton();
        pnlConPass = new javax.swing.JPanel();
        lblShowConPassword = new javax.swing.JLabel();
        txtConPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pnlPassword = new javax.swing.JPanel();
        lblShowPassword = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pnlOldPass = new javax.swing.JPanel();
        lblShowOldPassword = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblSirkol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(12, 150, 156));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 798));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Centsible 209 50.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("CONFIRM");
        btnConfirm.setBorderColor(new java.awt.Color(12, 150, 156));
        btnConfirm.setFocusable(false);
        btnConfirm.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnConfirm.setRadius(60);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 170, 60));

        pnlConPass.setBackground(new java.awt.Color(12, 150, 156));
        pnlConPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlConPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowConPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowConPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowConPasswordMouseClicked(evt);
            }
        });
        pnlConPass.add(lblShowConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 50));

        txtConPass.setBackground(new java.awt.Color(12, 150, 156));
        txtConPass.setFont(new java.awt.Font("ITC Souvenir", 0, 20)); // NOI18N
        txtConPass.setText("Confirm Password");
        txtConPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtConPassCaretUpdate(evt);
            }
        });
        txtConPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConPassFocusLost(evt);
            }
        });
        txtConPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPassKeyPressed(evt);
            }
        });
        pnlConPass.add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 400, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlConPass.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 50));

        jPanel1.add(pnlConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 500, 50));

        pnlPassword.setBackground(new java.awt.Color(12, 150, 156));
        pnlPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPasswordMouseClicked(evt);
            }
        });
        pnlPassword.add(lblShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 50));

        txtPass.setBackground(new java.awt.Color(12, 150, 156));
        txtPass.setFont(new java.awt.Font("ITC Souvenir", 0, 20)); // NOI18N
        txtPass.setText("New Password");
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCaretUpdate(evt);
            }
        });
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        pnlPassword.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 400, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlPassword.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 50));

        jPanel1.add(pnlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 500, 50));

        pnlOldPass.setBackground(new java.awt.Color(12, 150, 156));
        pnlOldPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlOldPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowOldPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowOldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowOldPasswordMouseClicked(evt);
            }
        });
        pnlOldPass.add(lblShowOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 50));

        txtOldPass.setBackground(new java.awt.Color(12, 150, 156));
        txtOldPass.setFont(new java.awt.Font("ITC Souvenir", 0, 20)); // NOI18N
        txtOldPass.setText("Old Password");
        txtOldPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtOldPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtOldPassCaretUpdate(evt);
            }
        });
        txtOldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOldPassFocusLost(evt);
            }
        });
        txtOldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOldPassKeyPressed(evt);
            }
        });
        pnlOldPass.add(txtOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 400, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlOldPass.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 50));

        jPanel1.add(pnlOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 500, 50));

        lblSirkol.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 26)); // NOI18N
        lblSirkol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Back Ground Circle 768 768.png"))); // NOI18N
        jPanel1.add(lblSirkol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(3, 47, 48));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/x.png"))); // NOI18N
        lblX.setPreferredSize(new java.awt.Dimension(30, 30));
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Minimize.png"))); // NOI18N
        lblMin.setToolTipText("");
        lblMin.setPreferredSize(new java.awt.Dimension(30, 30));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1298, Short.MAX_VALUE)
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Back Button 74 74.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        cp.confirmChangeAdmin(txtOldPass, txtPass, txtConPass, username, this);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void lblShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPasswordMouseClicked
        passFlag = cp.showPassword(passFlag, txtPass, lblShowPassword);
    }//GEN-LAST:event_lblShowPasswordMouseClicked

    private void txtPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCaretUpdate
        password = txtPass.getText();
    }//GEN-LAST:event_txtPassCaretUpdate

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        cp.passFocusGained(txtPass, password, passFlag);
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        password = cp.passFocusLost(txtPass, password);
    }//GEN-LAST:event_txtPassFocusLost

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        cp.checkKeyPressed(evt, txtOldPass, txtPass, txtConPass);
    }//GEN-LAST:event_txtPassKeyPressed

    private void lblShowConPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowConPasswordMouseClicked
        conPassFlag = cp.showConfirmPassword(conPassFlag, txtConPass,
            lblShowConPassword);
    }//GEN-LAST:event_lblShowConPasswordMouseClicked

    private void txtConPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConPassCaretUpdate
        conPass = txtConPass.getText();
    }//GEN-LAST:event_txtConPassCaretUpdate

    private void txtConPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusGained
        cp.conPassFocusGained(txtConPass, conPass, conPassFlag);
    }//GEN-LAST:event_txtConPassFocusGained

    private void txtConPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusLost
        conPass = cp.conPassFocusLost(txtConPass, conPass);
    }//GEN-LAST:event_txtConPassFocusLost

    private void txtConPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPassKeyPressed
        cp.checkKeyPressed(evt, txtOldPass, txtPass, txtConPass);
    }//GEN-LAST:event_txtConPassKeyPressed

    private void lblShowOldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowOldPasswordMouseClicked
        oldPassFlag = cp.showOldPassword(oldPassFlag, txtOldPass, lblShowOldPassword);
    }//GEN-LAST:event_lblShowOldPasswordMouseClicked

    private void txtOldPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtOldPassCaretUpdate
        oldPass = txtOldPass.getText();
    }//GEN-LAST:event_txtOldPassCaretUpdate

    private void txtOldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldPassFocusGained
        cp.oldPassFocusGained(txtOldPass, oldPass, oldPassFlag);
    }//GEN-LAST:event_txtOldPassFocusGained

    private void txtOldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldPassFocusLost
        oldPass = cp.oldPassFocusLost(txtOldPass, oldPass);
    }//GEN-LAST:event_txtOldPassFocusLost

    private void txtOldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPassKeyPressed
        cp.checkKeyPressed(evt, txtOldPass, txtPass, txtConPass);
    }//GEN-LAST:event_txtOldPassKeyPressed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        new AdminInfo().setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        UserFunctions.logOut(this);
    }//GEN-LAST:event_lblXMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private centsible.components.CustomButton btnConfirm;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblShowConPassword;
    private javax.swing.JLabel lblShowOldPassword;
    private javax.swing.JLabel lblShowPassword;
    private javax.swing.JLabel lblSirkol;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel pnlConPass;
    private javax.swing.JPanel pnlOldPass;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPasswordField txtConPass;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
