package centsible.frames.user;

import centsible.datas.Accounts;
import centsible.functions.AuditFunction;
import centsible.functions.GeneralFunction;
import centsible.functions.SavingsFunction;
import centsible.functions.UserFunctions;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class FundAction extends javax.swing.JFrame {

    int xMouse = 0, yMouse = 0;

    DecimalFormat df = new DecimalFormat("#,##0.00");
    SavingsFunction sf;

    String amount;

    public static int choice;
    public static int moveChoice;

    public FundAction() {
        initComponents();
        setLocationRelativeTo(null);

        sf = new SavingsFunction();

        txtAmountToAdd.getParent().requestFocus();
        lblFF.setText(SavingsFunction.savingsType);

        if (moveChoice > 1) {
            lblAvailBal.setText("Available Funds");
            lblBalanceAfter.setText("Savings After");
        }
        lblMoney.setText(df.format(sf.getBalance(moveChoice, 
                UserFunctions.username)));
        lblMoney2.setText(df.format(sf.getBalance(moveChoice, 
                UserFunctions.username)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPeso = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblGlobe = new javax.swing.JLabel();
        lblAvailBal = new javax.swing.JLabel();
        lblPhp = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        lblBalanceAfter = new javax.swing.JLabel();
        lblPhp1 = new javax.swing.JLabel();
        lblMoney2 = new javax.swing.JLabel();
        lblFF = new javax.swing.JLabel();
        btnConfirm = new centsible.components.CustomButton();
        txtAmountToAdd = new javax.swing.JTextField();
        lblSirkol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 798));

        jPanel1.setBackground(new java.awt.Color(12, 150, 156));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeso.setFont(new java.awt.Font("ITC Souvenir", 0, 35)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPeso.setText("PHP");
        jPanel1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 80, 42));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Centsible 209 50.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Back Button 74 74.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 670, -1, -1));

        lblGlobe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/baboy.png"))); // NOI18N
        jPanel1.add(lblGlobe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        lblAvailBal.setFont(new java.awt.Font("Lovelo Black", 0, 20)); // NOI18N
        lblAvailBal.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailBal.setText("AVAILABLE BALANCE");
        jPanel1.add(lblAvailBal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        lblPhp.setFont(new java.awt.Font("ITC Souvenir", 0, 18)); // NOI18N
        lblPhp.setForeground(new java.awt.Color(255, 255, 255));
        lblPhp.setText("PHP");
        jPanel1.add(lblPhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        lblMoney.setFont(new java.awt.Font("ITC Souvenir", 0, 18)); // NOI18N
        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMoney.setText("0.00");
        jPanel1.add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 220, 90, -1));

        lblBalanceAfter.setFont(new java.awt.Font("Lovelo Black", 0, 20)); // NOI18N
        lblBalanceAfter.setForeground(new java.awt.Color(255, 255, 255));
        lblBalanceAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalanceAfter.setText("BALANCE AFTER");
        jPanel1.add(lblBalanceAfter, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 190, 170, -1));

        lblPhp1.setFont(new java.awt.Font("ITC Souvenir", 0, 18)); // NOI18N
        lblPhp1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhp1.setText("PHP");
        jPanel1.add(lblPhp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        lblMoney2.setFont(new java.awt.Font("ITC Souvenir", 0, 18)); // NOI18N
        lblMoney2.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMoney2.setText("0.00");
        jPanel1.add(lblMoney2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 100, -1));

        lblFF.setFont(new java.awt.Font("Lovelo Black", 0, 40)); // NOI18N
        lblFF.setForeground(new java.awt.Color(3, 47, 48));
        lblFF.setText("FAMILY FUNDS");
        jPanel1.add(lblFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 270, 70));

        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("CONFIRM");
        btnConfirm.setBorderColor(new java.awt.Color(12, 150, 156));
        btnConfirm.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        btnConfirm.setRadius(60);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 180, 50));

        txtAmountToAdd.setBackground(new java.awt.Color(119, 196, 199));
        txtAmountToAdd.setFont(new java.awt.Font("ITC Souvenir", 0, 35)); // NOI18N
        txtAmountToAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAmountToAdd.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtAmountToAdd.setText("0.00");
        txtAmountToAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        txtAmountToAdd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtAmountToAddCaretUpdate(evt);
            }
        });
        txtAmountToAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountToAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountToAddFocusLost(evt);
            }
        });
        txtAmountToAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountToAddKeyTyped(evt);
            }
        });
        jPanel1.add(txtAmountToAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 270, 50));

        lblSirkol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Back Ground Circle 768 768.png"))); // NOI18N
        jPanel1.add(lblSirkol, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(3, 47, 48));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/x.png"))); // NOI18N
        lblX.setPreferredSize(new java.awt.Dimension(30, 30));
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Minimize.png"))); // NOI18N
        lblMin.setToolTipText("");
        lblMin.setPreferredSize(new java.awt.Dimension(30, 30));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1294, Short.MAX_VALUE)
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        new CheckFunds().setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        AuditFunction au = new AuditFunction();
        GeneralFunction gf = new GeneralFunction();

        String x = "";
        String y = "";

        double amount = Double.parseDouble(this.amount);

        if (moveChoice > 1) {

            for (Accounts a : GeneralFunction.list) {
                if (a.getUsername().equals(UserFunctions.username)) {
                    switch (FundAction.choice) {
                        case 1:
                            if (a.getFamilySavings() >= amount) {
                                a.setFamilySavings(a.getFamilySavings() 
                                        - amount);
                                x = "Moved " + df.format(amount) + " of Family "
                                        + "Funds to their Account";
                                y = "Retrieved money from Family Funds";
                            } else {
                                JOptionPane.showMessageDialog(null, 
                                        "Insufficient Funds.");
                            }
                            break;
                        case 2:
                            if (a.getOwnSavings() >= amount) {
                                a.setOwnSavings(a.getOwnSavings() - amount);
                                x = "Moved " + df.format(amount) + " of Own "
                                        + "Funds to their Account";
                                y = "Retrieved money from Own Funds";
                            } else {
                                JOptionPane.showMessageDialog(null, 
                                        "Insufficient Funds.");
                            }
                            break;
                    }
                    a.setBalance(a.getBalance() + amount);
                    GeneralFunction.rewrite();
                    gf.writeTransaction(UserFunctions.userID, y, "+" 
                            + df.format(amount));
                    JOptionPane.showMessageDialog(null, 
                            "Funds successfully moved.");
                    au.createAudit(UserFunctions.username, x);
                    this.dispose();
                    new CheckFunds().setVisible(true);
                    break;
                }
            }
        } else {

            for (Accounts a : GeneralFunction.list) {
                if (a.getUsername().equals(UserFunctions.username)) {
                    if (a.getBalance() >= amount) {
                        switch (FundAction.choice) {
                            case 1:
                                a.setFamilySavings(a.getFamilySavings() 
                                        + amount);
                                x = "Added "+ df.format(amount) 
                                        + " to Family Funds";
                                y = "Added money to Family Funds";
                                break;
                            case 2:
                                a.setOwnSavings(a.getOwnSavings() + amount);
                                x = "Added "+ df.format(amount) 
                                        + " to Own Funds";
                                y = "Added money to Own Funds";
                                break;
                        }
                        a.setBalance(a.getBalance() - amount);
                        GeneralFunction.rewrite();
                        au.createAudit(UserFunctions.username, x);
                        gf.writeTransaction(UserFunctions.userID, y, "-" 
                                + df.format(amount));
                        JOptionPane.showMessageDialog(null, 
                                "Funds successfully added.");
                        this.dispose();
                        new CheckFunds().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, 
                                "Insufficient Balance.");
                    }
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtAmountToAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountToAddKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_PERIOD)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountToAddKeyTyped

    private void txtAmountToAddCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAmountToAddCaretUpdate
        double fund;

        if (txtAmountToAdd.getText().length() > 0) {
            fund = Double.parseDouble(txtAmountToAdd.getText());
        } else {
            fund = 0;
        }
        fund = sf.getBalance(moveChoice, UserFunctions.username) - fund;

        lblMoney2.setText(df.format(fund));
    }//GEN-LAST:event_txtAmountToAddCaretUpdate

    private void txtAmountToAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountToAddFocusGained
        txtAmountToAdd.setText("");
        txtAmountToAdd.setText(amount);
    }//GEN-LAST:event_txtAmountToAddFocusGained

    private void txtAmountToAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountToAddFocusLost
        amount = txtAmountToAdd.getText();

        try {
            if (amount.substring(amount.length() - 2).equals("00")
                    && amount.indexOf('.') > -1) {
                amount = amount.substring(0, amount.length() - 3);
            }
        } catch (Exception e) {
        }

        if (amount.trim().length() != 0 && !amount.trim().equals("0.00")) {
            txtAmountToAdd.setText(df.format(Double.parseDouble(amount)));
        } else {
            txtAmountToAdd.setText("0.00");
            amount = "";
        }
    }//GEN-LAST:event_txtAmountToAddFocusLost

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        UserFunctions.logOut(this);
    }//GEN-LAST:event_lblXMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundAction().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private centsible.components.CustomButton btnConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvailBal;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBalanceAfter;
    private javax.swing.JLabel lblFF;
    private javax.swing.JLabel lblGlobe;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblMoney2;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPhp;
    private javax.swing.JLabel lblPhp1;
    private javax.swing.JLabel lblSirkol;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextField txtAmountToAdd;
    // End of variables declaration//GEN-END:variables
}
