package centsible.frames.user;

import centsible.functions.UserFunctions;
import java.text.DecimalFormat;

public class Homescreen extends javax.swing.JFrame {

    int xMouse = 0, yMouse = 0;
    
    public Homescreen(String username) {
        initComponents();
        setLocationRelativeTo(null);

        DecimalFormat df = new DecimalFormat("#,##0.00");

        UserFunctions.username = username;
        UserFunctions.balance = UserFunctions.getBalance(username);

        lblMoney.setText(df.format(UserFunctions.balance));

        lblUsername.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBankTransfer = new javax.swing.JLabel();
        lblSavings = new javax.swing.JLabel();
        lblPayBills = new javax.swing.JLabel();
        lblSendMoney = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblAvailBal = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPhp = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnCashIn = new centsible.components.CustomButton();
        lblSirkol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        customButton1 = new centsible.components.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(12, 150, 156));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 798));
        jPanel1.setLayout(null);

        lblBankTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Bank Transfer 272 211.png"))); // NOI18N
        lblBankTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBankTransferMouseClicked(evt);
            }
        });
        jPanel1.add(lblBankTransfer);
        lblBankTransfer.setBounds(370, 240, 260, 200);

        lblSavings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/savings.png"))); // NOI18N
        lblSavings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSavingsMouseClicked(evt);
            }
        });
        jPanel1.add(lblSavings);
        lblSavings.setBounds(740, 240, 250, 200);

        lblPayBills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Pay Bills 272 211.png"))); // NOI18N
        lblPayBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPayBillsMouseClicked(evt);
            }
        });
        jPanel1.add(lblPayBills);
        lblPayBills.setBounds(370, 460, 240, 200);

        lblSendMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/sendmoney.png"))); // NOI18N
        lblSendMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSendMoneyMouseClicked(evt);
            }
        });
        jPanel1.add(lblSendMoney);
        lblSendMoney.setBounds(740, 460, 240, 200);

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/user.png"))); // NOI18N
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblUser);
        lblUser.setBounds(1260, 50, 60, 70);

        lblAvailBal.setFont(new java.awt.Font("Lovelo Black", 0, 28)); // NOI18N
        lblAvailBal.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailBal.setText("AVAILABLE BALANCE");
        jPanel1.add(lblAvailBal);
        lblAvailBal.setBounds(560, 80, 270, 90);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Logo (Dark) 158 158.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(40, 50, 160, 160);

        lblUsername.setFont(new java.awt.Font("Lovelo Black", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USER NAME");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(1070, 70, 200, 40);

        lblPhp.setFont(new java.awt.Font("ITC Souvenir", 0, 24)); // NOI18N
        lblPhp.setForeground(new java.awt.Color(255, 255, 255));
        lblPhp.setText("PHP");
        jPanel1.add(lblPhp);
        lblPhp.setBounds(530, 160, 60, 30);

        lblMoney.setFont(new java.awt.Font("ITC Souvenir", 0, 24)); // NOI18N
        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMoney.setText("0.00");
        jPanel1.add(lblMoney);
        lblMoney.setBounds(600, 150, 160, 50);

        btnCashIn.setForeground(new java.awt.Color(255, 255, 255));
        btnCashIn.setText("Cash In");
        btnCashIn.setBorderColor(new java.awt.Color(12, 150, 156));
        btnCashIn.setFont(new java.awt.Font("ITC Souvenir", 0, 14)); // NOI18N
        btnCashIn.setRadius(35);
        btnCashIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashInActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashIn);
        btnCashIn.setBounds(790, 160, 80, 30);

        lblSirkol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Back Ground Circle 768 768.png"))); // NOI18N
        jPanel1.add(lblSirkol);
        lblSirkol.setBounds(300, 30, 800, 770);

        jPanel2.setBackground(new java.awt.Color(3, 47, 48));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/x.png"))); // NOI18N
        lblX.setPreferredSize(new java.awt.Dimension(30, 30));
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Minimize.png"))); // NOI18N
        lblMin.setToolTipText("");
        lblMin.setPreferredSize(new java.awt.Dimension(30, 30));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1298, Short.MAX_VALUE)
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 30);

        customButton1.setForeground(new java.awt.Color(255, 255, 255));
        customButton1.setText("Transaction");
        customButton1.setBorderColor(new java.awt.Color(12, 150, 156));
        customButton1.setFont(new java.awt.Font("ITC Souvenir", 0, 26)); // NOI18N
        customButton1.setRadius(60);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton1);
        customButton1.setBounds(1070, 690, 240, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBankTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBankTransferMouseClicked
        new ChooseBank().setVisible(true);
        BankInfo.name = new UserFunctions().getFullName(UserFunctions.username);
        dispose();
    }//GEN-LAST:event_lblBankTransferMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        UserFunctions.logOut(this);
    }//GEN-LAST:event_lblXMouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        setState(Homescreen.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblPayBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayBillsMouseClicked
        new PayBillsChoice().setVisible(true);
        FillInfoPayBills.name = new UserFunctions()
                .getFullName(UserFunctions.username);
        dispose();
    }//GEN-LAST:event_lblPayBillsMouseClicked

    private void lblSavingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSavingsMouseClicked
        new Savings().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSavingsMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        new UserInfo().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblSendMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendMoneyMouseClicked
        new SendMoney().setVisible(true);
        SendMoney.name = new UserFunctions()
                .getFullName(UserFunctions.username);
        dispose();
    }//GEN-LAST:event_lblSendMoneyMouseClicked

    private void btnCashInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashInActionPerformed
        HowToCashIn htci = new HowToCashIn();
        htci.setVisible(true);
        htci.setFocusableWindowState(true);
    }//GEN-LAST:event_btnCashInActionPerformed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        new TransactionHistory().setVisible(true);
        dispose();
    }//GEN-LAST:event_customButton1ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homescreen("Sample").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private centsible.components.CustomButton btnCashIn;
    private centsible.components.CustomButton customButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvailBal;
    private javax.swing.JLabel lblBankTransfer;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblPayBills;
    private javax.swing.JLabel lblPhp;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JLabel lblSendMoney;
    private javax.swing.JLabel lblSirkol;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
