/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package centsible.frames.startup;

import centsible.components.CustomFont;
import centsible.functions.ForgotPasswordFunction;
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author lukea
 */
public class ForgotPassword extends javax.swing.JFrame {

    int xMouse, yMouse;
    int passFlag = 0, conPassFlag = 0;

    String email, password, confirmPassword, verificationCode;

    ForgotPasswordFunction fpf;

    public ForgotPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        setComps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        dragFrame = new javax.swing.JPanel();
        pnlGreen = new javax.swing.JPanel();
        pnlWhite = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblGreetings = new javax.swing.JLabel();
        btnSignin = new centsible.components.CustomButton();
        pnlLogin = new javax.swing.JPanel();
        pnlVerificationCode = new javax.swing.JPanel();
        txtVerCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlPassword = new javax.swing.JPanel();
        lblShowPassword = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pnlConPass = new javax.swing.JPanel();
        lblShowConPassword = new javax.swing.JLabel();
        txtConPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pnlEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfirm = new centsible.components.CustomButton();
        btnSendOTP = new centsible.components.CustomButton();
        jLabel1 = new javax.swing.JLabel();

        dateChooser.setForeground(new java.awt.Color(3, 47, 48));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragFrameMouseDragged(evt);
            }
        });
        dragFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragFrameMousePressed(evt);
            }
        });
        dragFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGreen.setBackground(new java.awt.Color(3, 47, 48));
        pnlGreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dragFrame.add(pnlGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        pnlWhite.setBackground(new java.awt.Color(255, 255, 255));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_bl.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mini_bl.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlWhiteLayout = new javax.swing.GroupLayout(pnlWhite);
        pnlWhite.setLayout(pnlWhiteLayout);
        pnlWhiteLayout.setHorizontalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWhiteLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addContainerGap())
        );
        pnlWhiteLayout.setVerticalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhiteLayout.createSequentialGroup()
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 400, Short.MAX_VALUE))
        );

        dragFrame.add(pnlWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 430, 440));

        getContentPane().add(dragFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        pnlSignup.setBackground(new java.awt.Color(3, 47, 48));

        lblGreetings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGreetings.setForeground(new java.awt.Color(255, 255, 255));
        lblGreetings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreetings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/Logo (ilaw).png"))); // NOI18N

        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("Sign in");
        btnSignin.setRadius(50);
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSignupLayout = new javax.swing.GroupLayout(pnlSignup);
        pnlSignup.setLayout(pnlSignupLayout);
        pnlSignupLayout.setHorizontalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGreetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSignupLayout.setVerticalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblGreetings)
                .addGap(103, 103, 103)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoginMouseClicked(evt);
            }
        });

        pnlVerificationCode.setBackground(new java.awt.Color(12, 150, 156));
        pnlVerificationCode.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlVerificationCode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVerCode.setBackground(new java.awt.Color(12, 150, 156));
        txtVerCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVerCode.setText("Verification Code");
        txtVerCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtVerCode.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtVerCodeCaretUpdate(evt);
            }
        });
        txtVerCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVerCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVerCodeFocusLost(evt);
            }
        });
        txtVerCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVerCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVerCodeKeyTyped(evt);
            }
        });
        pnlVerificationCode.add(txtVerCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userImages/verification.png"))); // NOI18N
        pnlVerificationCode.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlPassword.setBackground(new java.awt.Color(12, 150, 156));
        pnlPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPasswordMouseClicked(evt);
            }
        });
        pnlPassword.add(lblShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 40));

        txtPass.setBackground(new java.awt.Color(12, 150, 156));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.setText("New Password");
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCaretUpdate(evt);
            }
        });
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        pnlPassword.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlPassword.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlConPass.setBackground(new java.awt.Color(12, 150, 156));
        pnlConPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlConPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowConPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowConPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowConPasswordMouseClicked(evt);
            }
        });
        pnlConPass.add(lblShowConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 40));

        txtConPass.setBackground(new java.awt.Color(12, 150, 156));
        txtConPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConPass.setText("Confirm Password");
        txtConPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtConPassCaretUpdate(evt);
            }
        });
        txtConPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConPassFocusLost(evt);
            }
        });
        txtConPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPassKeyPressed(evt);
            }
        });
        pnlConPass.add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlConPass.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlEmail.setBackground(new java.awt.Color(12, 150, 156));
        pnlEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(12, 150, 156));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmailCaretUpdate(evt);
            }
        });
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        pnlEmail.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 260, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        pnlEmail.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESET PASSWORD");

        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm");
        btnConfirm.setBorderColor(new java.awt.Color(3, 47, 48));
        btnConfirm.setRadius(50);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnSendOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnSendOTP.setText("SEND OTP");
        btnSendOTP.setBorderColor(new java.awt.Color(3, 47, 48));
        btnSendOTP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSendOTP.setRadius(35);
        btnSendOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendOTPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("ITC Souvenir", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your verification code will be sent to your email.");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(pnlVerificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlConPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlConPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVerificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnSendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(102, 102, 102)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 430, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragFrameMouseDragged

    private void dragFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragFrameMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPasswordMouseClicked
        passFlag = fpf.showPassword(passFlag, txtPass, lblShowPassword);
    }//GEN-LAST:event_lblShowPasswordMouseClicked

    private void txtPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCaretUpdate
        password = txtPass.getText();
    }//GEN-LAST:event_txtPassCaretUpdate

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        fpf.passFocusGained(txtPass, password, passFlag);
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        password = fpf.passFocusLost(txtPass, password);
    }//GEN-LAST:event_txtPassFocusLost

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        fpf.checkKeyPressed(evt, txtEmail, txtPass, txtConPass, txtVerCode);
    }//GEN-LAST:event_txtPassKeyPressed

    private void lblShowConPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowConPasswordMouseClicked
        conPassFlag = fpf.showConfirmPassword(conPassFlag, txtConPass,
                lblShowConPassword);
    }//GEN-LAST:event_lblShowConPasswordMouseClicked

    private void txtConPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConPassCaretUpdate
        confirmPassword = txtConPass.getText();
    }//GEN-LAST:event_txtConPassCaretUpdate

    private void txtConPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusGained
        fpf.conPassFocusGained(txtConPass, confirmPassword, conPassFlag);
    }//GEN-LAST:event_txtConPassFocusGained

    private void txtConPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusLost
        confirmPassword = fpf.conPassFocusLost(txtConPass, confirmPassword);
    }//GEN-LAST:event_txtConPassFocusLost

    private void txtConPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPassKeyPressed
        fpf.checkKeyPressed(evt, txtEmail, txtPass, txtConPass, txtVerCode);
    }//GEN-LAST:event_txtConPassKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        fpf.checkKeyPressed(evt, txtEmail, txtPass, txtConPass, txtVerCode);
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        email = fpf.emailFocusLost(txtEmail, email);
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        fpf.emailFocusGained(txtEmail, email);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmailCaretUpdate
        email = txtEmail.getText();
    }//GEN-LAST:event_txtEmailCaretUpdate

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        fpf.confirmChange(txtEmail, txtPass, txtConPass, txtVerCode);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSigninActionPerformed

    private void pnlLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoginMouseClicked
        txtVerCode.getParent().requestFocusInWindow();
    }//GEN-LAST:event_pnlLoginMouseClicked

    private void txtVerCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerCodeKeyPressed
        fpf.checkKeyPressed(evt, txtEmail, txtPass, txtConPass, txtVerCode);
    }//GEN-LAST:event_txtVerCodeKeyPressed

    private void txtVerCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVerCodeFocusLost
        verificationCode = fpf.verifiyFocusLost(txtVerCode, verificationCode);
    }//GEN-LAST:event_txtVerCodeFocusLost

    private void txtVerCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVerCodeFocusGained
        fpf.verifyFocusGained(txtVerCode, verificationCode);
    }//GEN-LAST:event_txtVerCodeFocusGained

    private void txtVerCodeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtVerCodeCaretUpdate
        verificationCode = txtVerCode.getText();
    }//GEN-LAST:event_txtVerCodeCaretUpdate

    private void btnSendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOTPActionPerformed
        fpf.sendOTP(txtEmail);
    }//GEN-LAST:event_btnSendOTPActionPerformed

    private void txtVerCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerCodeKeyTyped
         char c = evt.getKeyChar();
        if (txtVerCode.getText().length() < 6) {
            if (!((c >= '0') && (c <= '9')
                    || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtVerCodeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    public void setComps() {
        getContentPane().setBackground(new Color(240, 240, 240));

        fpf = new ForgotPasswordFunction(txtEmail, txtPass, txtConPass, 
                txtVerCode);

        CustomFont cf = new CustomFont();

        cf.setFont(pnlVerificationCode, 18);
        cf.setFont(pnlEmail, 18);
        cf.setFont(pnlPassword, 18);
        cf.setFont(pnlConPass, 18);
        cf.setFont(btnConfirm, 18);
        cf.setFont(lblGreetings, 18);
        cf.setFont(btnSignin, 18);

        txtPass.setEchoChar((char) 0);
        txtConPass.setEchoChar((char) 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private centsible.components.CustomButton btnConfirm;
    private centsible.components.CustomButton btnSendOTP;
    private centsible.components.CustomButton btnSignin;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JPanel dragFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblShowConPassword;
    private javax.swing.JLabel lblShowPassword;
    private javax.swing.JPanel pnlConPass;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlGreen;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JPanel pnlVerificationCode;
    private javax.swing.JPanel pnlWhite;
    private javax.swing.JPasswordField txtConPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtVerCode;
    // End of variables declaration//GEN-END:variables
}
