package centsible.frames.startup;

import centsible.components.CustomFont;
import centsible.functions.SignupFunction;
import javax.swing.JFrame;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;

/**
 *
 * @author lukea
 */
public class Signup extends javax.swing.JFrame {

    int xMouse, yMouse;
    int year;
    int passFlag = 0, conPassFlag = 0;

    String fullName, username, email, password, confirmPassword;

    SignupFunction sf;

    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
        setComps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        dragFrame = new javax.swing.JPanel();
        pnlGreen = new javax.swing.JPanel();
        pnlWhite = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblGreetings = new javax.swing.JLabel();
        lblMessage1 = new javax.swing.JLabel();
        btnSignin = new centsible.components.CustomButton();
        pnlLogin = new javax.swing.JPanel();
        pnlFullName = new javax.swing.JPanel();
        txtFullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pnlUsername = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlPassword = new javax.swing.JPanel();
        lblShowPassword = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pnlConPass = new javax.swing.JPanel();
        lblShowConPassword = new javax.swing.JLabel();
        txtConPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pnlDate = new javax.swing.JPanel();
        lblCalendar = new javax.swing.JLabel();
        txtBirthdate = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSignup = new centsible.components.CustomButton();

        dateChooser.setForeground(new java.awt.Color(3, 47, 48));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragFrameMouseDragged(evt);
            }
        });
        dragFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragFrameMousePressed(evt);
            }
        });
        dragFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGreen.setBackground(new java.awt.Color(3, 47, 48));
        pnlGreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dragFrame.add(pnlGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        pnlWhite.setBackground(new java.awt.Color(255, 255, 255));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_bl.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mini_bl.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlWhiteLayout = new javax.swing.GroupLayout(pnlWhite);
        pnlWhite.setLayout(pnlWhiteLayout);
        pnlWhiteLayout.setHorizontalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWhiteLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addContainerGap())
        );
        pnlWhiteLayout.setVerticalGroup(
            pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhiteLayout.createSequentialGroup()
                .addGroup(pnlWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 400, Short.MAX_VALUE))
        );

        dragFrame.add(pnlWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 430, 440));

        getContentPane().add(dragFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        pnlSignup.setBackground(new java.awt.Color(3, 47, 48));

        lblGreetings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGreetings.setForeground(new java.awt.Color(255, 255, 255));
        lblGreetings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreetings.setText("Hello, Dear Citicents!");

        lblMessage1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage1.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage1.setText("If you already have an account sign in here");

        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("Sign in");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSignupLayout = new javax.swing.GroupLayout(pnlSignup);
        pnlSignup.setLayout(pnlSignupLayout);
        pnlSignupLayout.setHorizontalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignupLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSignupLayout.setVerticalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lblGreetings)
                .addGap(54, 54, 54)
                .addComponent(lblMessage1)
                .addGap(94, 94, 94)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoginMouseClicked(evt);
            }
        });

        pnlFullName.setBackground(new java.awt.Color(12, 150, 156));
        pnlFullName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlFullName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullName.setBackground(new java.awt.Color(12, 150, 156));
        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFullName.setText("Full Name");
        txtFullName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFullName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFullNameCaretUpdate(evt);
            }
        });
        txtFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullNameFocusLost(evt);
            }
        });
        txtFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFullNameKeyPressed(evt);
            }
        });
        pnlFullName.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        pnlFullName.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlUsername.setBackground(new java.awt.Color(12, 150, 156));
        pnlUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(12, 150, 156));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setText("Username");
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsername.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtUsernameCaretUpdate(evt);
            }
        });
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        pnlUsername.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        pnlUsername.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlPassword.setBackground(new java.awt.Color(12, 150, 156));
        pnlPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPasswordMouseClicked(evt);
            }
        });
        pnlPassword.add(lblShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 40));

        txtPass.setBackground(new java.awt.Color(12, 150, 156));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.setText("Password");
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCaretUpdate(evt);
            }
        });
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        pnlPassword.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlPassword.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlConPass.setBackground(new java.awt.Color(12, 150, 156));
        pnlConPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlConPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowConPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblShowConPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowConPasswordMouseClicked(evt);
            }
        });
        pnlConPass.add(lblShowConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 40));

        txtConPass.setBackground(new java.awt.Color(12, 150, 156));
        txtConPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConPass.setText("Confirm Password");
        txtConPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtConPassCaretUpdate(evt);
            }
        });
        txtConPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConPassFocusLost(evt);
            }
        });
        txtConPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPassKeyPressed(evt);
            }
        });
        pnlConPass.add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        pnlConPass.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        pnlDate.setBackground(new java.awt.Color(12, 150, 156));
        pnlDate.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDateMouseClicked(evt);
            }
        });
        pnlDate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        pnlDate.add(lblCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        txtBirthdate.setEditable(false);
        txtBirthdate.setBackground(new java.awt.Color(12, 150, 156));
        txtBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBirthdate.setText("Date of Birth");
        txtBirthdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBirthdate.setFocusable(false);
        txtBirthdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBirthdateMouseClicked(evt);
            }
        });
        pnlDate.add(txtBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 40));

        pnlEmail.setBackground(new java.awt.Color(12, 150, 156));
        pnlEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(12, 150, 156));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmailCaretUpdate(evt);
            }
        });
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        pnlEmail.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        pnlEmail.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREATE ACCOUNT");

        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign up");
        btnSignup.setRadius(50);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(pnlFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlConPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 430, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragFrameMouseDragged

    private void dragFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragFrameMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void txtFullNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFullNameCaretUpdate
        fullName = txtFullName.getText();
    }//GEN-LAST:event_txtFullNameCaretUpdate

    private void txtFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullNameFocusGained
        sf.fullNameFocusGained(txtFullName, fullName);
    }//GEN-LAST:event_txtFullNameFocusGained

    private void txtFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullNameFocusLost
        fullName = sf.fullNameFocusLost(txtFullName, fullName);
    }//GEN-LAST:event_txtFullNameFocusLost

    private void txtFullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullNameKeyPressed
        sf.checkKeyPressed(evt, txtFullName, txtUsername, txtEmail,
                txtBirthdate, txtPass, txtConPass, this);
    }//GEN-LAST:event_txtFullNameKeyPressed

    private void txtUsernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUsernameCaretUpdate
        username = txtUsername.getText();
    }//GEN-LAST:event_txtUsernameCaretUpdate

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        sf.usernameFocusGained(txtUsername, username);
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        username = sf.usernameFocusLost(txtUsername, username);
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        sf.checkKeyPressed(evt, txtFullName, txtUsername, txtEmail,
                txtBirthdate, txtPass, txtConPass, this);
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void lblShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPasswordMouseClicked
        passFlag = sf.showPassword(passFlag, txtPass, lblShowPassword);
    }//GEN-LAST:event_lblShowPasswordMouseClicked

    private void txtPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCaretUpdate
        password = txtPass.getText();
    }//GEN-LAST:event_txtPassCaretUpdate

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        sf.passFocusGained(txtPass, password, passFlag);
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        password = sf.passFocusLost(txtPass, password);
    }//GEN-LAST:event_txtPassFocusLost

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        sf.checkKeyPressed(evt, txtFullName, txtUsername, txtEmail,
                txtBirthdate, txtPass, txtConPass, this);
    }//GEN-LAST:event_txtPassKeyPressed

    private void lblShowConPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowConPasswordMouseClicked
        conPassFlag = sf.showPassword(conPassFlag, txtConPass,
                lblShowConPassword);
    }//GEN-LAST:event_lblShowConPasswordMouseClicked

    private void txtConPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConPassCaretUpdate
        confirmPassword = txtConPass.getText();
    }//GEN-LAST:event_txtConPassCaretUpdate

    private void txtConPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusGained
        sf.conPassFocusGained(txtConPass, confirmPassword, conPassFlag);
    }//GEN-LAST:event_txtConPassFocusGained

    private void txtConPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPassFocusLost
        confirmPassword = sf.conPassFocusLost(txtConPass, confirmPassword);
    }//GEN-LAST:event_txtConPassFocusLost

    private void txtConPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPassKeyPressed
        sf.checkKeyPressed(evt, txtFullName, txtUsername, txtEmail,
                txtBirthdate, txtPass, txtConPass, this);
    }//GEN-LAST:event_txtConPassKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        sf.checkKeyPressed(evt, txtFullName, txtUsername, txtEmail,
                txtBirthdate, txtPass, txtConPass, this);
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        email = sf.emailFocusLost(txtEmail, email);
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        sf.emailFocusGained(txtEmail, email);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmailCaretUpdate
        email = txtEmail.getText();
    }//GEN-LAST:event_txtEmailCaretUpdate

    private void txtBirthdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBirthdateMouseClicked
        dateChooser.setDateFormat("MMMM dd, yyyy");
        dateChooser.setTextRefernce(txtBirthdate);
        dateChooser.showPopup();
        txtUsername.getParent().requestFocusInWindow();
    }//GEN-LAST:event_txtBirthdateMouseClicked

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        sf.verifyCreation(txtFullName, txtUsername, txtBirthdate, txtEmail, 
                txtPass, txtConPass, this);
        OTPVerification.ref = this;
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSigninActionPerformed

    private void pnlDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDateMouseClicked
        dateChooser.setDateFormat("MMMM dd, yyyy");
        dateChooser.setTextRefernce(txtBirthdate);
        dateChooser.showPopup();
    }//GEN-LAST:event_pnlDateMouseClicked

    private void pnlLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoginMouseClicked
        txtUsername.getParent().requestFocusInWindow();
    }//GEN-LAST:event_pnlLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    public void setComps() {
        getContentPane().setBackground(new Color(240, 240, 240));

        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                SignupFunction.day = date.getDay();
                SignupFunction.month = date.getMonth();
                SignupFunction.year = date.getYear();
                
                System.out.println(year);
                System.out.println(date.getMonth() + " " + date.getDay() + ", "
                        + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });

        sf = new SignupFunction(txtFullName, txtUsername, txtBirthdate,
                txtEmail, txtPass, txtConPass);

        CustomFont cf = new CustomFont();

        cf.setFont(pnlFullName, 18);
        cf.setFont(pnlUsername, 18);
        cf.setFont(pnlDate, 18);
        cf.setFont(pnlEmail, 18);
        cf.setFont(pnlPassword, 18);
        cf.setFont(pnlConPass, 18);
        cf.setFont(btnSignup, 18);
        cf.setFont(lblGreetings, 18);
        cf.setFont(lblMessage1, 16);
        cf.setFont(btnSignin, 18);

        txtPass.setEchoChar((char) 0);
        txtConPass.setEchoChar((char) 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private centsible.components.CustomButton btnSignin;
    private centsible.components.CustomButton btnSignup;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JPanel dragFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCalendar;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblMessage1;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblShowConPassword;
    private javax.swing.JLabel lblShowPassword;
    private javax.swing.JPanel pnlConPass;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlFullName;
    private javax.swing.JPanel pnlGreen;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JPanel pnlUsername;
    private javax.swing.JPanel pnlWhite;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JPasswordField txtConPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
